# Generated by Django 5.2.5 on 2025-09-01 15:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('strategy_type', models.CharField(choices=[('trend_following', 'Trend Following'), ('mean_reversion', 'Mean Reversion'), ('breakout', 'Breakout'), ('scalping', 'Scalping'), ('swing', 'Swing Trading'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('symbol', models.CharField(default='ES', help_text='Trading symbol', max_length=20)),
                ('timeframe', models.CharField(default='1m', help_text='Strategy timeframe', max_length=3)),
                ('position_size', models.DecimalField(decimal_places=2, default=1.0, help_text='Position size in lots', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100.0)])),
                ('max_positions', models.PositiveIntegerField(default=1, help_text='Max simultaneous positions')),
                ('stop_loss_pips', models.PositiveIntegerField(default=50, help_text='Stop loss in pips')),
                ('take_profit_pips', models.PositiveIntegerField(default=100, help_text='Take profit in pips')),
                ('rules', models.JSONField(default=list, help_text='List of strategy rules')),
                ('backtest_enabled', models.BooleanField(default=True)),
                ('backtest_start_date', models.DateTimeField(blank=True, null=True)),
                ('backtest_end_date', models.DateTimeField(blank=True, null=True)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('losing_trades', models.PositiveIntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('profit_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Strategies',
                'ordering': ['-created_at'],
            },
        ),
    ]
