# Generated by Django 5.2.5 on 2025-09-02 08:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='backtest_enabled',
            new_name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='strategy',
            unique_together={('user', 'name')},
        ),
        migrations.AddField(
            model_name='strategy',
            name='entry_rules',
            field=models.JSONField(default=dict, help_text='Entry conditions'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='exit_rules',
            field=models.JSONField(default=dict, help_text='Exit conditions'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, help_text='Strategy description'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(help_text='Strategy name', max_length=200),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='stop_loss_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('points', 'Points')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='stop_loss_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='take_profit_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('points', 'Points')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='take_profit_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('2.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='timeframe',
            field=models.CharField(default='5m', help_text='Data timeframe', max_length=3),
        ),
        migrations.AlterModelTable(
            name='strategy',
            table='strategies',
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Backtest start date')),
                ('end_date', models.DateTimeField(help_text='Backtest end date')),
                ('initial_capital', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=10)),
                ('slippage', models.DecimalField(decimal_places=4, default=Decimal('0.5'), max_digits=10)),
                ('total_return', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_return_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('max_drawdown_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('profit_factor', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('avg_win', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('avg_loss', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('largest_win', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('largest_loss', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('rating', models.CharField(choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], default='Poor', max_length=20)),
                ('rating_color', models.CharField(default='#ff6b6b', max_length=7)),
                ('summary_description', models.TextField(blank=True)),
                ('execution_time', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('data_source', models.CharField(choices=[('database', 'Database'), ('parquet', 'Parquet')], default='database', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backtest_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_date', models.DateTimeField()),
                ('exit_date', models.DateTimeField()),
                ('quantity', models.IntegerField(default=1)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slippage', models.DecimalField(decimal_places=4, max_digits=10)),
                ('net_pnl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(help_text='Exit reason (Take Profit, Stop Loss, etc.)', max_length=50)),
                ('duration', models.BigIntegerField(help_text='Trade duration in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='strategies.backtestresult')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['entry_date'],
            },
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='backtest_end_date',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='backtest_start_date',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='losing_trades',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='max_drawdown',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='max_positions',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='position_size',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='profit_factor',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='round_turn_commissions',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='slippage',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='status',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='stop_loss_pips',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='strategy_type',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='take_profit_pips',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='total_trades',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='win_rate',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='winning_trades',
        ),
    ]
