# Generated by Django 5.2.5 on 2025-08-29 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='user',
        ),
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='title',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
