# Generated by Django 5.2.5 on 2025-09-02 12:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_alter_strategy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='initial_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000'), help_text='Initial capital for backtesting', max_digits=15),
        ),
    ]
