# Generated by Django 5.2.5 on 2025-08-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_remove_strategy_name_remove_strategy_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='language',
            field=models.CharField(choices=[('PY', 'Python'), ('CS', 'C#')], default='PY', max_length=10),
        ),
        migrations.AddField(
            model_name='strategy',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='max_drawdown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='quantconnect_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='sharpe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BACKTESTING', 'Backtesting'), ('LIVE', 'Live Trading')], default='INACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='strategy',
            name='total_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='total_trades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
