# Generated by Django 5.2.5 on 2025-08-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_strategy_is_synced_strategy_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ['-last_sync'], 'verbose_name_plural': 'Strategies'},
        ),
        migrations.AddField(
            model_name='strategy',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='strategy',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='strategy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('csharp', 'C#'), ('fsharp', 'F#')], default='python', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='max_drawdown',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quantconnect_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategy',
            name='sharpe_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='status',
            field=models.CharField(choices=[('live', 'Live Trading'), ('paper', 'Paper Trading'), ('backtest', 'Backtest'), ('research', 'Research')], default='backtest', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='total_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='win_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
