# Generated by Django 5.2.5 on 2025-09-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_strategy_initial_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='avg_trade_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='calmar_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='expectancy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='max_consecutive_losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='max_consecutive_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='recovery_factor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='sortino_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='trades_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='volatility',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
