# Generated by Django 5.2.5 on 2025-09-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0004_backtestresult_avg_trade_duration_and_more'),
    ]

    operations = [
    ]
