# Generated by Django 5.2.5 on 2025-09-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0005_auto_20250902_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='stop_loss_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('points', 'Points'), ('ticks', 'Ticks'), ('atr', 'ATR')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='take_profit_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('points', 'Points'), ('ticks', 'Ticks'), ('atr', 'ATR')], default='percentage', max_length=20),
        ),
    ]
