# Generated by Django 5.2.5 on 2025-09-03 03:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0006_update_risk_management_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityCurvePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Point timestamp')),
                ('equity_value', models.DecimalField(decimal_places=2, help_text='Portfolio value at this point', max_digits=15)),
                ('drawdown', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Drawdown at this point', max_digits=10)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_curve', to='strategies.backtestresult')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equity_points', to='strategies.trade')),
            ],
            options={
                'db_table': 'equity_curve_points',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['backtest', 'timestamp'], name='equity_curv_backtes_69d882_idx')],
            },
        ),
    ]
