# Generated by Django 5.2.5 on 2025-09-04 22:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0007_add_equity_curve_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='qc_backtest_id',
            field=models.CharField(blank=True, help_text='QuantConnect backtest ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='qc_compile_id',
            field=models.CharField(blank=True, help_text='QuantConnect compile ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='qc_last_sync',
            field=models.DateTimeField(blank=True, help_text='Last QuantConnect sync timestamp', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='qc_progress',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='QuantConnect backtest progress %', max_digits=5),
        ),
        migrations.AddField(
            model_name='strategy',
            name='qc_project_id',
            field=models.CharField(blank=True, help_text='QuantConnect project ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='qc_results',
            field=models.JSONField(blank=True, help_text='QuantConnect backtest results', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='qc_status',
            field=models.CharField(default='Unknown', help_text='QuantConnect backtest status', max_length=50),
        ),
    ]
