# Generated by Django 5.2.5 on 2025-09-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0007_add_equity_curve_model'),
    ]

    operations = [
    ]
