# Generated by Django 5.2.5 on 2025-09-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0008_auto_20250905_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='qc_progress',
            field=models.JSONField(blank=True, default=dict, help_text='QuantConnect progress data', null=True),
        ),
    ]
