# Generated by Django 5.2.5 on 2025-09-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0009_strategy_qc_progress'),
    ]

    operations = [
    ]
