# Generated by Django 5.2.5 on 2025-09-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0010_change_qc_progress_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='qc_progress',
            field=models.TextField(blank=True, default='{}', help_text='QuantConnect progress data', null=True),
        ),
    ]
