# Generated by Django 5.2.5 on 2025-09-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0011_alter_strategy_qc_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='qc_progress',
        ),
    ]
