# Generated by Django 5.2.5 on 2025-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0012_remove_strategy_qc_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='qc_status',
            field=models.CharField(default='pending', help_text='QuantConnect status', max_length=50),
        ),
    ]
