# Generated by Django 5.2.5 on 2025-09-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0013_strategy_qc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='qc_status',
        ),
    ]
