# Generated by Django 5.2.5 on 2025-09-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0014_remove_strategy_qc_status'),
    ]

    operations = [
    ]
