# Generated by Django 5.2.5 on 2025-09-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0007_add_equity_curve_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this strategy is public/example for all users'),
        ),
    ]
