# Generated by Django 5.2.5 on 2025-09-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0015_remove_qc_fields'),
        ('strategies', '0016_strategy_is_public'),
    ]

    operations = [
    ]
