# Generated by Django 5.2.5 on 2025-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0017_merge_0015_remove_qc_fields_0016_strategy_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', help_text='Strategy status', max_length=20),
        ),
    ]
