# Generated by Django 5.2.5 on 2025-09-19 09:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0019_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['entry_time']},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_strategy_favorite',
        ),
        migrations.RemoveIndex(
            model_name='equitycurvepoint',
            name='equity_curv_backtes_69d882_idx',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='avg_loss',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='avg_trade_duration',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='avg_win',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='calmar_ratio',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='expectancy',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='largest_loss',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='largest_win',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='max_consecutive_losses',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='max_consecutive_wins',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='max_drawdown_percent',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='rating_color',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='recovery_factor',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='sortino_ratio',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='summary_description',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='total_return_percent',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='trades_per_month',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='volatility',
        ),
        migrations.RemoveField(
            model_name='equitycurvepoint',
            name='equity_value',
        ),
        migrations.RemoveField(
            model_name='equitycurvepoint',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='action',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='exit_date',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='net_pnl',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='slippage',
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='annualized_return',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='equitycurvepoint',
            name='equity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='trade',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='initial_capital',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='max_drawdown',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='sharpe_ratio',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='slippage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='total_return',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='equitycurvepoint',
            name='drawdown',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='equitycurvepoint',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='entry_rules',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='exit_rules',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='initial_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='stop_loss_type',
            field=models.CharField(default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='stop_loss_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='take_profit_type',
            field=models.CharField(default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='take_profit_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='timeframe',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'strategy')},
        ),
        migrations.AlterModelTable(
            name='backtestresult',
            table=None,
        ),
        migrations.AlterModelTable(
            name='equitycurvepoint',
            table=None,
        ),
        migrations.AlterModelTable(
            name='strategy',
            table=None,
        ),
        migrations.AlterModelTable(
            name='trade',
            table=None,
        ),
    ]
