# Generated by Django 5.2.5 on 2025-11-25 14:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0020_alter_trade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestresult',
            name='annualized_return',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='max_drawdown',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='profit_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='sharpe_ratio',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='total_return',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='win_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7),
        ),
    ]
