# Generated by Django 5.2.5 on 2025-08-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Nombre del archivo importado', max_length=255)),
                ('file_path', models.TextField(help_text='Ruta del archivo')),
                ('symbol', models.CharField(help_text='Símbolo del futuro', max_length=20)),
                ('timeframe', models.CharField(help_text='Timeframe de los datos', max_length=3)),
                ('total_rows', models.IntegerField(default=0, help_text='Total de filas en el archivo')),
                ('imported_rows', models.IntegerField(default=0, help_text='Filas importadas exitosamente')),
                ('skipped_rows', models.IntegerField(default=0, help_text='Filas omitidas')),
                ('start_date', models.DateTimeField(blank=True, help_text='Fecha de inicio de los datos', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Fecha de fin de los datos', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falló')),
                ('processing_time', models.FloatField(blank=True, help_text='Tiempo de procesamiento en segundos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_import_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='ES', help_text='Símbolo del futuro (ej: ES para E-mini S&P 500)', max_length=20)),
                ('date', models.DateTimeField(help_text='Fecha y hora de la vela')),
                ('timeframe', models.CharField(choices=[('1m', '1 Minuto'), ('5m', '5 Minutos'), ('15m', '15 Minutos'), ('30m', '30 Minutos'), ('1h', '1 Hora'), ('4h', '4 Horas'), ('1d', '1 Día')], default='1m', help_text='Timeframe de los datos', max_length=3)),
                ('open_price', models.DecimalField(decimal_places=2, help_text='Precio de apertura', max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, help_text='Precio más alto', max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, help_text='Precio más bajo', max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, help_text='Precio de cierre', max_digits=10)),
                ('volume', models.BigIntegerField(help_text='Volumen de transacciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'historical_data',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', 'date', 'timeframe'], name='historical__symbol_b8366a_idx'), models.Index(fields=['date'], name='historical__date_80140f_idx'), models.Index(fields=['symbol', 'timeframe'], name='historical__symbol_c8f41f_idx')],
                'unique_together': {('symbol', 'date', 'timeframe')},
            },
        ),
    ]
