# Generated by Django 5.2.5 on 2025-09-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimportlog',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Data end date', null=True),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if failed'),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='file_name',
            field=models.CharField(help_text='Imported file name', max_length=255),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='file_path',
            field=models.TextField(help_text='File path'),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='imported_rows',
            field=models.IntegerField(default=0, help_text='Successfully imported rows'),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Processing time in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='skipped_rows',
            field=models.IntegerField(default=0, help_text='Skipped rows'),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Data start date', null=True),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='symbol',
            field=models.CharField(help_text='Future symbol', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='timeframe',
            field=models.CharField(help_text='Data timeframe', max_length=3),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='total_rows',
            field=models.IntegerField(default=0, help_text='Total rows in file'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='close_price',
            field=models.DecimalField(decimal_places=2, help_text='Closing price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='date',
            field=models.DateTimeField(help_text='Candle date and time'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='high_price',
            field=models.DecimalField(decimal_places=2, help_text='Highest price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='low_price',
            field=models.DecimalField(decimal_places=2, help_text='Lowest price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='open_price',
            field=models.DecimalField(decimal_places=2, help_text='Opening price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='symbol',
            field=models.CharField(default='ES', help_text='Future symbol (e.g., ES for E-mini S&P 500)', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='timeframe',
            field=models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day')], default='1m', help_text='Data timeframe', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='volume',
            field=models.BigIntegerField(help_text='Transaction volume'),
        ),
    ]
