# Generated by Django 5.2.5 on 2025-09-01 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sma_periods', models.JSONField(default=list)),
                ('ema_periods', models.JSONField(default=list)),
                ('rsi_period', models.IntegerField(default=14)),
                ('macd_fast', models.IntegerField(default=12)),
                ('macd_slow', models.IntegerField(default=26)),
                ('macd_signal', models.IntegerField(default=9)),
                ('atr_period', models.IntegerField(default=14)),
                ('bb_period', models.IntegerField(default=20)),
                ('bb_std_dev', models.DecimalField(decimal_places=1, default=2.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('sma_20', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sma_50', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ema_20', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ema_50', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vwap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('macd_line', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('macd_histogram', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stoch_k', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stoch_d', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('atr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bb_upper', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bb_middle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bb_lower', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_results', to='indicators.symbol')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='indicators__symbol__56520d_idx'), models.Index(fields=['timestamp'], name='indicators__timesta_5c30b3_idx')],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('trend', 'Trend Analysis'), ('momentum', 'Momentum Analysis'), ('volatility', 'Volatility Analysis'), ('custom', 'Custom Analysis')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('analysis_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='indicators.symbol')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'analysis_type', 'timestamp')},
            },
        ),
    ]
